// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * ChecksumInfoDTO is JSON-friendly checksum state for the advanced panel.
 */
export class ChecksumInfoDTO {
    "hasDump": boolean;
    "ok": boolean;
    "current": number;
    "expected": number;
    "sumMod": number;
    "leader": number;

    /** Creates a new ChecksumInfoDTO instance. */
    constructor($$source: Partial<ChecksumInfoDTO> = {}) {
        if (!("hasDump" in $$source)) {
            this["hasDump"] = false;
        }
        if (!("ok" in $$source)) {
            this["ok"] = false;
        }
        if (!("current" in $$source)) {
            this["current"] = 0;
        }
        if (!("expected" in $$source)) {
            this["expected"] = 0;
        }
        if (!("sumMod" in $$source)) {
            this["sumMod"] = 0;
        }
        if (!("leader" in $$source)) {
            this["leader"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ChecksumInfoDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): ChecksumInfoDTO {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ChecksumInfoDTO($$parsedSource as Partial<ChecksumInfoDTO>);
    }
}

/**
 * StatusDTO is JSON-friendly state for the UI.
 */
export class StatusDTO {
    "connected": boolean;
    "port": string;
    "hasDump": boolean;
    "leader": number;
    "leaderMin": number;
    "leaderMax": number;
    "checksumOk": boolean;

    /** Creates a new StatusDTO instance. */
    constructor($$source: Partial<StatusDTO> = {}) {
        if (!("connected" in $$source)) {
            this["connected"] = false;
        }
        if (!("port" in $$source)) {
            this["port"] = "";
        }
        if (!("hasDump" in $$source)) {
            this["hasDump"] = false;
        }
        if (!("leader" in $$source)) {
            this["leader"] = 0;
        }
        if (!("leaderMin" in $$source)) {
            this["leaderMin"] = 0;
        }
        if (!("leaderMax" in $$source)) {
            this["leaderMax"] = 0;
        }
        if (!("checksumOk" in $$source)) {
            this["checksumOk"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new StatusDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): StatusDTO {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new StatusDTO($$parsedSource as Partial<StatusDTO>);
    }
}
