// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * StudioService exposes EEPROM studio methods to the React frontend.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Connect opens the camera session on port (scene 1).
 */
export function Connect(port: string): $CancellablePromise<void> {
    return $Call.ByID(3064483691, port);
}

/**
 * Disconnect closes the serial session.
 */
export function Disconnect(): $CancellablePromise<void> {
    return $Call.ByID(2949748685);
}

/**
 * Dump reads 512B and disconnects (scene 2).
 */
export function Dump(): $CancellablePromise<void> {
    return $Call.ByID(102037313);
}

/**
 * GetChecksumInfo returns checksum state from the EEPROM mirror.
 */
export function GetChecksumInfo(): $CancellablePromise<$models.ChecksumInfoDTO> {
    return $Call.ByID(2952795254).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * GetDumpHex returns HxD-style hex for the local EEPROM mirror (highlights 0x017F).
 */
export function GetDumpHex(): $CancellablePromise<string> {
    return $Call.ByID(1480176068);
}

/**
 * GetStatus returns current studio state for React.
 */
export function GetStatus(): $CancellablePromise<$models.StatusDTO> {
    return $Call.ByID(3177458899).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * IsConnected reports whether a session is open.
 */
export function IsConnected(): $CancellablePromise<boolean> {
    return $Call.ByID(879899246);
}

/**
 * LeaderDragToValue maps drag position 0..1 to dec 6 (55mm) .. 31 (5mm).
 */
export function LeaderDragToValue(t: number): $CancellablePromise<number> {
    return $Call.ByID(3818779850, t);
}

/**
 * LeaderValueToDrag inverts LeaderDragToValue for UI initialization.
 */
export function LeaderValueToDrag(value: number): $CancellablePromise<number> {
    return $Call.ByID(3667746928, value);
}

/**
 * ListPorts returns available serial port names.
 */
export function ListPorts(): $CancellablePromise<string[]> {
    return $Call.ByID(1085660849).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * PromptSaveDump opens a native save dialog and writes the EEPROM mirror. Returns true if saved.
 */
export function PromptSaveDump(): $CancellablePromise<boolean> {
    return $Call.ByID(1968506742);
}

/**
 * RefreshDump reconnects, reads 512B into the mirror, and disconnects (no save dialog).
 */
export function RefreshDump(): $CancellablePromise<void> {
    return $Call.ByID(1956412656);
}

/**
 * SaveDumpTo writes the EEPROM mirror to a user-chosen path (512B .bin).
 */
export function SaveDumpTo(path: string): $CancellablePromise<void> {
    return $Call.ByID(3018837569, path);
}

/**
 * SetLocale sets log and error language for the backend ("zh", "en", or "ja").
 */
export function SetLocale(locale: string): $CancellablePromise<void> {
    return $Call.ByID(1486625791, locale);
}

/**
 * WriteChecksumOnly reconnects and writes 0x017F only (MODIFY failure recovery).
 */
export function WriteChecksumOnly(): $CancellablePromise<void> {
    return $Call.ByID(2898343719);
}

/**
 * WriteLeader writes 0x169 (dec 6–31) with checksum (scene 3 MODIFY).
 */
export function WriteLeader(length: number): $CancellablePromise<void> {
    return $Call.ByID(2035054367, length);
}

// Private type creation functions
const $$createType0 = $models.ChecksumInfoDTO.createFrom;
const $$createType1 = $models.StatusDTO.createFrom;
const $$createType2 = $Create.Array($Create.Any);
